services:
  lunatv:
    image: lunatv:custom
    container_name: lunatv
    restart: unless-stopped
    ports:
      - '8899:3000'
    volumes:
      - ./lunatv/cache:/app/data
    environment:
      - NODE_ENV=production
      - GO_PROXY_URL=http://127.0.0.1:8080
      - DISABLE_SECURE_COOKIES=true
      # Cache Configuration
      - DOUBAN_DATA_CACHE_TTL_MINUTES=1440
      - IMAGE_CACHE_TTL_DAYS=30
      - NEXT_PUBLIC_SITE_NAME=MoonTV
      - ANNOUNCEMENT=
      # Auth
      - USERNAME=admin
      - PASSWORD=admin_1234
      - NEXT_PUBLIC_STORAGE_TYPE=redis
      - REDIS_URL=redis://lunatv-redis:6379
    networks:
      - media-net

networks:
  media-net:
    external: true
