version: '3'

services:
  lunatv:
    image: lunatv:custom
    container_name: lunatv
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./cache:/app/data
    environment:
      - NODE_ENV=production
      # Cache Configuration
    - DOUBAN_DATA_CACHE_TTL_MINUTES=1440
    - IMAGE_CACHE_TTL_DAYS=30
    - NEXT_PUBLIC_SITE_NAME=MoonTV
    - ANNOUNCEMENT=
      # Auth
      - USERNAME=admin
      - PASSWORD=wonderpig888